--- 
environments: "Options allowed by Rails::Configuration in Rails 1.1.2.\r\n\
  From http://glu.ttono.us/articles/2006/05/22/configuring-rails-environments-the-cheat-sheet\r\n\
  \r\n\
  General Options\r\n  breakpoint_server\r\n    Whether or not to use the breakpoint server (boolean)\r\n  cache_classes\r\n    Whether or not classes should be cached (set to false if you want application classes to be reloaded on each request) \r\n  connection_adapters     \r\n    The list of connection adapters to load.\r\n    By default, all connection adapters are loaded. You can set this to be just the adapter(s) you will use to reduce your application\xE2\x80\x99s load time. \r\n  controller_paths\r\n    The list of paths that should be searched for controllers.\r\n    Defaults to app/controllers and components.\r\n  database_configuration_file\r\n    The path to the database configuration file to use.\r\n    Defaults to config/database.yml.\r\n  frameworks\r\n    The list of rails framework components that should be loaded.\r\n    Defaults to :active_record, :action_controller, :action_view, :action_mailer, and \r\n    :action_web_service.\r\n  load_paths\r\n    An array of additional paths to prepend to the load path.\r\n    By default, all app, lib, vendor and mock paths are included in this list.\r\n  log_level\r\n    The log level to use for the default Rails logger.\r\n    In production mode, this defaults to :info. In development mode, it defaults to :debug.\r\n  log_path\r\n    The path to the log file to use.\r\n    Defaults to log/#{environment}.log (e.g. log/development.log or log/production.log).\r\n  logger\r\n    The specific logger to use.\r\n    By default, a logger will be created and initialized using #log_path and #log_level, but a programmer may specifically set the logger to use via this accessor and it will be used directly.\r\n  view_path\r\n    The root of the application's views.\r\n    Defaults to app/views.\r\n  whiny_nils\r\n    Set to true if you want to be warned (noisily) when you try to invoke any method of nil. \r\n    Set to false for the standard Ruby behavior.\r\n  plugin_paths\r\n    The path to the root of the plugins directory.\r\n    By default, it is in vendor/plugins.\r\n\
  \r\n\
  ActiveRecord Options\r\n\
  Each of these options should be prepended with config.active_record. when \r\n\
  used with a Rails::Initializer do |config| block.\r\n\
  \r\n  primary_key_prefix_type\r\n    Accessor for the prefix type that will be prepended to every primary key column name. \r\n    The options are :table_name and :table_name_with_underscore. If the first is specified, the Product class will look for \"productid\" instead of \"id\" as the primary column. If the latter is specified, the Product class will look for \"product_id\" instead of \"id\". Remember that this is a global setting for all Active Records.\r\n  table_name_prefix\r\n    The string to prepend to every table name.\r\n    By default, the prefix is an empty string\r\n  table_name_suffix\r\n    The same as table_name_prefix, but it appends the string to the table name.\r\n  pluralize_table_names\r\n    Indicates whether or not table names should be the pluralized versions of the corresponding class names.\r\n    Defaults to true.\r\n  colorize_logging\r\n    Should logs have ANSI color codes in logging statments?\r\n    Defaults to true\r\n  default_timezone\r\n    Determines whether to use Time.local (using :local) or Time.utc (using :utc) when pulling dates and times from the database.\r\n    Defaults to :local by default.\r\n  allow_concurrency\r\n    Determines whether or not to use a connection for each thread, or a single shared connection for all threads.\r\n    Defaults to false. Set to true if you're writing a threaded application.\r\n  generate_read_methods\r\n    Determines whether to speed up access by generating optimized reader methods to avoid expensive calls to method_missing when accessing attributes by name. \r\n    You might want to set this to false in development mode, because the methods would be regenerated on each request.\r\n  schema_format\r\n    Specifies whether to dump the database in ruby or sql. It takes :ruby or :sql as options, and defaults to :ruby\r\n\
  \r\n\
  ActionController Options\r\n\
  Each of these options should be prepended with config.action_controller. when \r\n\
  used with a Rails::Initializer do |config| block.\r\n\
  \r\n  view_controller_internals\r\n    Determines whether the view has access to controller internals @request, @response, @session, and @template.\r\n  assert_host\r\n    Prepends all the URL-generating helpers from AssetHelper (eg. image_tag)\r\n  consider_all_requests_local\r\n    All requests are considered local by default (true), so everyone will be exposed to \r\n    detailed debugging screens on errors.\r\n    Defaults to true\r\n  debug_routes\r\n    Enable or disable the collection of failure information for RoutingErrors.\r\n    Defaults to true.\r\n  allow_concurrency\r\n    Controls whether the application is thread-safe.\r\n    Defaults to false.\r\n  param_parsers\r\n    Lets you register handlers wich will process the http body and add parameters to the @params hash.\r\n    Defaults to { Mime::XML => :xml_simple }\r\n  template_root\r\n    Sets the default template location. For example, a call to render(\"test/template\") \r\n    will be converted to \"#{template_root}/test/template.rhtml\" logger\r\n    Can be set to nil for no logging or a logger conforming to the interface of Log4r or the default Ruby 1.8+ Logger class.\r\n  ignore_missing_templates\r\n    Turn on ignore_missing_templates if you want to unit test actions without making the associated templates.\r\n\
  \r\n\
  ActionView Options\r\n\
  Each of these options should be prepended with config.action_view. when \r\n\
  used with a Rails::Initializer do |config| block.\r\n\
  \r\n  cache_template_loading\r\n    Specify whether file modification times should be checked to see if a template needs recompilation\r\n  cache_template_extensions\r\n    Specify whether file extension lookup should be cached. Should be false for development environments.\r\n    Defaults to true.\r\n  local_assigns_support_string_keys\r\n    Specify whether local_assigns should be able to use string keys.\r\n    Defaults to true.\r\n    String keys are deprecated and will be removed shortly.\r\n  debug_rjs\r\n    Specify whether RJS responses should be wrapped in a try/catch block that alert()s \r\n    the caught exception (and then re-raises it).\r\n    Defaults to false.\r\n  logger\r\n    Can be set to nil for no logging or a logger conforming to the interface of Log4r or the default Ruby 1.8+ Logger class."
