--- 
textmate_rails: "\xE2\x8C\x98 = command\n\
  \xE2\x8C\x83 = control\n\
  \xE2\x8C\xA5 = option\n\
  \xE2\x87\xA7 = shift\n\n\
  Meta\n  Find shortcut                             \xE2\x8C\x83 \xE2\x8C\x98 T\n  \n\
  File Navigation\n  go to file                                  \xE2\x8C\x98 T\n  go to line                                  \xE2\x8C\x98 L\n  go to method                              \xE2\x87\xA7 \xE2\x8C\x98 T\n  find in project                           \xE2\x87\xA7 \xE2\x8C\x98 F\n  reveal in project                         \xE2\x8C\x83 \xE2\x8C\x98 R\n  go to related file                     \xE2\x8C\xA5 \xE2\x8C\x98 DOWN\n  go to...                            \xE2\x87\xA7  \xE2\x8C\xA5 \xE2\x8C\x98 DOWN           \n\n\
  Selection\n  select word                                 \xE2\x8C\x83 W\n  select line                               \xE2\x87\xA7 \xE2\x8C\x98 L\n  select block                              \xE2\x87\xA7 \xE2\x8C\x98 B\n\n\
  Deleting\n  Delete rest of the line                      \xE2\x8C\x83K\n  Delete line                               \xE2\x87\xA7  \xE2\x8C\x83K\n  Join line                                 \xE2\x87\xA7  \xE2\x8C\x83J\n  \n\
  Toggle\n  Quotes                                       \xE2\x8C\x83\"\n  Symbol                                       \xE2\x8C\x83:\n  \n\
  Editing\n  code completion                          Escape\n  fold / unfold                                F1\n  comment selection                           \xE2\x8C\x98 /\n  indent selection                   \xE2\x8C\x98 [  and \xE2\x8C\x98 ]\n  move selection                      \xE2\x8C\x83 \xE2\x8C\x98 (arrow)\n  edit selection                            \xE2\x8C\xA5 \xE2\x8C\x98 A\n  column selection                       \xE2\x8C\xA5 (drag)\n\n\n\
  Views\n  wrap selection as link                    \xE2\x8C\x83 \xE2\x87\xA7 L\n  <%  %>                                      \xE2\x8C\x83 \xE2\x87\xA7 > (twice)\n  <%=  %>                                     \xE2\x8C\x83 \xE2\x87\xA7 > (once)\n  \n  create partial from selection             \xE2\x8C\x83 \xE2\x87\xA7 H\n  \n\
  Commands                                  \xE2\x8C\x83 \xE2\x8C\xA5 \xE2\x8C\x98 C\n  run file as ruby                            \xE2\x8C\x98 R\n  start irb                                 \xE2\x8C\x83 \xE2\x87\xA7 I\n\n\
  Snippets                                  \xE2\x8C\x83 \xE2\x8C\xA5 \xE2\x8C\x98 S\n                                      Tab Trigger\n  class class_name                          class\n  def method_name                             def\n  each { |element| ... }                     each\n  for element in collection                 forin\n  if condition                       if or ifelse\n  unless condition                         unless\n  :key => \"value\"                               :\n  flash[:notice] = \"...\"                    flash\n  logger.info \"...\"                          logi\n  assert_equal value, @o.attr                  ae\n  redirect_to options                     rec[ai]\n  render :action => \"action\"                   ra\n  render :partial => \"item\"               rp[loc]\n  create_table \"table\" ...                    mct\n  create several: table.column : , :         mccc\n\n  has_many :objects ...                        hm\n  belongs_to :object ...                       bt\n  validates_presence_of :attr ...            vpif\n\n                                          Hot Key\n  =>                                          \xE2\x8C\x83 L\n  params[:id]                                 \xE2\x8C\x83 P\n  session[:user]                              \xE2\x8C\x83 J"
